package com.froy.magicalitem.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.froy.magicalitem.dao.CategoriesDao;
import com.froy.magicalitem.dao.MagicalItemsDao;
import com.froy.magicalitem.dao.SpellsDao;
import com.froy.magicalitem.dao.FeatsDao;
import com.froy.magicalitem.dao.ItemSpellsDao;
import com.froy.magicalitem.dao.ItemFeatsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CategoriesDao.createTable(db, ifNotExists);
        MagicalItemsDao.createTable(db, ifNotExists);
        SpellsDao.createTable(db, ifNotExists);
        FeatsDao.createTable(db, ifNotExists);
        ItemSpellsDao.createTable(db, ifNotExists);
        ItemFeatsDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CategoriesDao.dropTable(db, ifExists);
        MagicalItemsDao.dropTable(db, ifExists);
        SpellsDao.dropTable(db, ifExists);
        FeatsDao.dropTable(db, ifExists);
        ItemSpellsDao.dropTable(db, ifExists);
        ItemFeatsDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CategoriesDao.class);
        registerDaoClass(MagicalItemsDao.class);
        registerDaoClass(SpellsDao.class);
        registerDaoClass(FeatsDao.class);
        registerDaoClass(ItemSpellsDao.class);
        registerDaoClass(ItemFeatsDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
