package com.froy.magicalitem.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.froy.magicalitem.dao.ItemFeats;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ITEM_FEATS.
*/
public class ItemFeatsDao extends AbstractDao<ItemFeats, Long> {

    public static final String TABLENAME = "ITEM_FEATS";

    /**
     * Properties of entity ItemFeats.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ItemId = new Property(1, Long.class, "itemId", false, "ITEM_ID");
        public final static Property FeatId = new Property(2, Long.class, "featId", false, "FEAT_ID");
    };

    private DaoSession daoSession;

    private Query<ItemFeats> magicalItems_ItemFeatsListQuery;
    private Query<ItemFeats> feats_ItemFeatsListQuery;

    public ItemFeatsDao(DaoConfig config) {
        super(config);
    }
    
    public ItemFeatsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ITEM_FEATS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ITEM_ID' INTEGER," + // 1: itemId
                "'FEAT_ID' INTEGER);"); // 2: featId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ITEM_FEATS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ItemFeats entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long itemId = entity.getItemId();
        if (itemId != null) {
            stmt.bindLong(2, itemId);
        }
 
        Long featId = entity.getFeatId();
        if (featId != null) {
            stmt.bindLong(3, featId);
        }
    }

    @Override
    protected void attachEntity(ItemFeats entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ItemFeats readEntity(Cursor cursor, int offset) {
        ItemFeats entity = new ItemFeats( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // itemId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // featId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ItemFeats entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItemId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setFeatId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ItemFeats entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ItemFeats entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "itemFeatsList" to-many relationship of MagicalItems. */
    public List<ItemFeats> _queryMagicalItems_ItemFeatsList(Long itemId) {
        synchronized (this) {
            if (magicalItems_ItemFeatsListQuery == null) {
                QueryBuilder<ItemFeats> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ItemId.eq(null));
                magicalItems_ItemFeatsListQuery = queryBuilder.build();
            }
        }
        Query<ItemFeats> query = magicalItems_ItemFeatsListQuery.forCurrentThread();
        query.setParameter(0, itemId);
        return query.list();
    }

    /** Internal query to resolve the "itemFeatsList" to-many relationship of Feats. */
    public List<ItemFeats> _queryFeats_ItemFeatsList(Long featId) {
        synchronized (this) {
            if (feats_ItemFeatsListQuery == null) {
                QueryBuilder<ItemFeats> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FeatId.eq(null));
                feats_ItemFeatsListQuery = queryBuilder.build();
            }
        }
        Query<ItemFeats> query = feats_ItemFeatsListQuery.forCurrentThread();
        query.setParameter(0, featId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMagicalItemsDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFeatsDao().getAllColumns());
            builder.append(" FROM ITEM_FEATS T");
            builder.append(" LEFT JOIN MAGICAL_ITEMS T0 ON T.'ITEM_ID'=T0.'_id'");
            builder.append(" LEFT JOIN FEATS T1 ON T.'FEAT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ItemFeats loadCurrentDeep(Cursor cursor, boolean lock) {
        ItemFeats entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        MagicalItems item = loadCurrentOther(daoSession.getMagicalItemsDao(), cursor, offset);
        entity.setItem(item);
        offset += daoSession.getMagicalItemsDao().getAllColumns().length;

        Feats itemFeats = loadCurrentOther(daoSession.getFeatsDao(), cursor, offset);
        entity.setItemFeats(itemFeats);

        return entity;    
    }

    public ItemFeats loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ItemFeats> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ItemFeats> list = new ArrayList<ItemFeats>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ItemFeats> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ItemFeats> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
