package com.froy.magicalitem.dao;

import java.util.List;
import com.froy.magicalitem.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SPELLS.
 */
public class Spells {

    private Long id;
    private String name;
    private String altname;
    private String school;
    private String subschool;
    private String descriptor;
    private String spellcraft_dc;
    private String level;
    private String components;
    private String casting_time;
    private String range;
    private String target;
    private String area;
    private String effect;
    private String duration;
    private String saving_throw;
    private String spell_resistance;
    private String short_description;
    private String to_develop;
    private String material_components;
    private String arcane_material_components;
    private String focus;
    private String description;
    private String xp_cost;
    private String arcane_focus;
    private String wizard_focus;
    private String verbal_components;
    private String sorcerer_focus;
    private String bard_focus;
    private String cleric_focus;
    private String druid_focus;
    private String full_text;
    private String reference;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SpellsDao myDao;

    private List<ItemSpells> itemSpellsList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Spells() {
    }

    public Spells(Long id) {
        this.id = id;
    }

    public Spells(Long id, String name, String altname, String school, String subschool, String descriptor, String spellcraft_dc, String level, String components, String casting_time, String range, String target, String area, String effect, String duration, String saving_throw, String spell_resistance, String short_description, String to_develop, String material_components, String arcane_material_components, String focus, String description, String xp_cost, String arcane_focus, String wizard_focus, String verbal_components, String sorcerer_focus, String bard_focus, String cleric_focus, String druid_focus, String full_text, String reference) {
        this.id = id;
        this.name = name;
        this.altname = altname;
        this.school = school;
        this.subschool = subschool;
        this.descriptor = descriptor;
        this.spellcraft_dc = spellcraft_dc;
        this.level = level;
        this.components = components;
        this.casting_time = casting_time;
        this.range = range;
        this.target = target;
        this.area = area;
        this.effect = effect;
        this.duration = duration;
        this.saving_throw = saving_throw;
        this.spell_resistance = spell_resistance;
        this.short_description = short_description;
        this.to_develop = to_develop;
        this.material_components = material_components;
        this.arcane_material_components = arcane_material_components;
        this.focus = focus;
        this.description = description;
        this.xp_cost = xp_cost;
        this.arcane_focus = arcane_focus;
        this.wizard_focus = wizard_focus;
        this.verbal_components = verbal_components;
        this.sorcerer_focus = sorcerer_focus;
        this.bard_focus = bard_focus;
        this.cleric_focus = cleric_focus;
        this.druid_focus = druid_focus;
        this.full_text = full_text;
        this.reference = reference;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSpellsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAltname() {
        return altname;
    }

    public void setAltname(String altname) {
        this.altname = altname;
    }

    public String getSchool() {
        return school;
    }

    public void setSchool(String school) {
        this.school = school;
    }

    public String getSubschool() {
        return subschool;
    }

    public void setSubschool(String subschool) {
        this.subschool = subschool;
    }

    public String getDescriptor() {
        return descriptor;
    }

    public void setDescriptor(String descriptor) {
        this.descriptor = descriptor;
    }

    public String getSpellcraft_dc() {
        return spellcraft_dc;
    }

    public void setSpellcraft_dc(String spellcraft_dc) {
        this.spellcraft_dc = spellcraft_dc;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getComponents() {
        return components;
    }

    public void setComponents(String components) {
        this.components = components;
    }

    public String getCasting_time() {
        return casting_time;
    }

    public void setCasting_time(String casting_time) {
        this.casting_time = casting_time;
    }

    public String getRange() {
        return range;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getEffect() {
        return effect;
    }

    public void setEffect(String effect) {
        this.effect = effect;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getSaving_throw() {
        return saving_throw;
    }

    public void setSaving_throw(String saving_throw) {
        this.saving_throw = saving_throw;
    }

    public String getSpell_resistance() {
        return spell_resistance;
    }

    public void setSpell_resistance(String spell_resistance) {
        this.spell_resistance = spell_resistance;
    }

    public String getShort_description() {
        return short_description;
    }

    public void setShort_description(String short_description) {
        this.short_description = short_description;
    }

    public String getTo_develop() {
        return to_develop;
    }

    public void setTo_develop(String to_develop) {
        this.to_develop = to_develop;
    }

    public String getMaterial_components() {
        return material_components;
    }

    public void setMaterial_components(String material_components) {
        this.material_components = material_components;
    }

    public String getArcane_material_components() {
        return arcane_material_components;
    }

    public void setArcane_material_components(String arcane_material_components) {
        this.arcane_material_components = arcane_material_components;
    }

    public String getFocus() {
        return focus;
    }

    public void setFocus(String focus) {
        this.focus = focus;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getXp_cost() {
        return xp_cost;
    }

    public void setXp_cost(String xp_cost) {
        this.xp_cost = xp_cost;
    }

    public String getArcane_focus() {
        return arcane_focus;
    }

    public void setArcane_focus(String arcane_focus) {
        this.arcane_focus = arcane_focus;
    }

    public String getWizard_focus() {
        return wizard_focus;
    }

    public void setWizard_focus(String wizard_focus) {
        this.wizard_focus = wizard_focus;
    }

    public String getVerbal_components() {
        return verbal_components;
    }

    public void setVerbal_components(String verbal_components) {
        this.verbal_components = verbal_components;
    }

    public String getSorcerer_focus() {
        return sorcerer_focus;
    }

    public void setSorcerer_focus(String sorcerer_focus) {
        this.sorcerer_focus = sorcerer_focus;
    }

    public String getBard_focus() {
        return bard_focus;
    }

    public void setBard_focus(String bard_focus) {
        this.bard_focus = bard_focus;
    }

    public String getCleric_focus() {
        return cleric_focus;
    }

    public void setCleric_focus(String cleric_focus) {
        this.cleric_focus = cleric_focus;
    }

    public String getDruid_focus() {
        return druid_focus;
    }

    public void setDruid_focus(String druid_focus) {
        this.druid_focus = druid_focus;
    }

    public String getFull_text() {
        return full_text;
    }

    public void setFull_text(String full_text) {
        this.full_text = full_text;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ItemSpells> getItemSpellsList() {
        if (itemSpellsList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ItemSpellsDao targetDao = daoSession.getItemSpellsDao();
            List<ItemSpells> itemSpellsListNew = targetDao._querySpells_ItemSpellsList(id);
            synchronized (this) {
                if(itemSpellsList == null) {
                    itemSpellsList = itemSpellsListNew;
                }
            }
        }
        return itemSpellsList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetItemSpellsList() {
        itemSpellsList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
